# Generated by Django 5.2.3 on 2025-08-17 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 17, 6, 34, 19, 806499, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
